package types

var Buildings = map[string]string{
	// === FAIRFAX CAMPUS ===
	"AB":     "Art and Design Building",
	"ACGC":   "Angel Cabrera Global Center",
	"AFC":    "Aquatic and Fitness Center",
	"AQ":     "Aquia Building",
	"BL":     "Blue Ridge Hall",
	"BUCHAN": "Buchanan Hall",
	"CAROW":  "Carow Hall",
	"CFA":    "Center for the Arts",
	"CH":     "College Hall",
	"DK":     "David J. King Hall",
	"E":      "East Building",
	"ENGR":   "Nguyen Engineering Building",
	"ENT":    "Enterprise Hall",
	"ESNHWR": "Eisenhower",
	"ESTSHR": "Eastern Shore",
	"EXPL":   "Exploratory Hall (formerly Science and Tech II)",
	"FENWCK": "Fenwick Library",
	"FH":     "Field House",
	"FIELD":  "Athletic Fields (West Campus)",
	"FINLEY": "Finley Building",
	"HNOVR":  "Hanover Hall",
	"HORIZN": "Horizon Hall",
	"HR":     "Hampton Roads",
	"HT":     "Harris Theater",
	"HUB":    "The Hub",
	"IN":     "Innovation Hall",
	"JC":     "Johnson Center",
	"KB":     "Krasnow Building",
	"KH":     "Krug Hall",
	"LH":     "Lecture Hall",
	"MAINST": "Main Street (9900 Main Street)",
	"MERTEN": "Merten Hall",
	"MTB":    "Music Theater Building",
	"PAB":    "de Laski Performing Arts Building",
	"PETRSN": "Peterson Hall",
	"PIEDMT": "Piedmont Hall",
	"PLANET": "Planetary Hall",
	"RAC":    "Recreation Athletic Complex",
	"ROGER":  "Roger Hall",
	"RSCH":   "Research Hall",
	"SNDBGE": "Sandbridge Hall",
	"SUBI":   "Student Union I",
	"T":      "Thompson Hall",
	"W":      "West Building",

	// === ARLINGTON CAMPUS (Mason Square) ===
	"ARL1":   "Hazel Hall",
	"ARLVM":  "Van Metre Hall (Formerly Founders Hall)",
	"ARLVSH": "Vernon Smith Hall",
	"ARFUSE": "Fuse at Mason Square",

	// === SCITECH CAMPUS (Prince William) ===
	"PW-ABR":  "Advanced Biomedical Research",
	"PW-CH":   "Colgan Hall",
	"PW-DH":   "Discovery Hall",
	"PW-FC":   "Freedom Aquatic and Fitness Center",
	"PW-KJH":  "Katherine Johnson Hall",
	"PW-LSEB": "Life Sciences and Engineering",

	// === OFF CAMPUS / OTHER ===
	"C":          "Commerce Building",
	"CBR":        "4260 Chain Bridge Road",
	"KOREA":      "Mason Korea",
	"OFF_CAMPUS": "Off Campus",
	"ON_LINE":    "Online",
}
